### ISSUE TITLE
failed on wp package install git@github.com:vccw-team/wp-cli-vackup.git

### ISSUE THREAD

**Issue by torounit** [vccw-team/wp-cli-vackup#4]
Show error on wp package install 
> Problem 1
    - The requested package vccw-team/wp-cli-vackup could not be found in any version, there may be a typo in the package name.

It is probably because composer.json name is not equal Github Repo name.

**Comment by miya0001** [comment]
Ah, you have to install it like following.
https://github.com/vccw-team/wp-cli-vackup#getting-started

This project hasn't  be accepted in package index.
We have to wait for another project of the WP-CLI org.
